# Generated by Django 6.0.3 on 2026-03-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('channel_id', models.CharField(max_length=128)),
                ('content_length', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='api_message_timesta_25d67f_idx'), models.Index(fields=['channel_id'], name='api_message_channel_b48318_idx'), models.Index(fields=['user_id'], name='api_message_user_id_81a8a9_idx')],
            },
        ),
    ]
