# Generated by Django 6.0.3 on 2026-03-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spam', 'Spam'), ('burst', 'Burst'), ('raid', 'Raid'), ('suspicious_join', 'Suspicious Join')], max_length=32)),
                ('channel_id', models.CharField(blank=True, max_length=64, null=True)),
                ('guild_id', models.CharField(blank=True, max_length=64, null=True)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
